// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pfklfbdpzknrbebglxho.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBma2xmYmRwemtucmJlYmdseGhvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDUwMTIwNjMsImV4cCI6MjA2MDU4ODA2M30.BtWKpxhD4YBqTf3BWL6N7xS876sie-Ri9GnLTwIYaLY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);